# Site settings
title: JeongYeop Lee (Nayak)
email: wjdduq914@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://leejeongyeop.github.io" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
github: "github.com/LeeJeongYeop"
github_url: "https://github.com/LeeJeongYeop"

# Build settings
markdown: kramdown